FROM python:3.9-slim


# DIRECTORY 
WORKDIR /app


COPY producer.py /app/producer.py


RUN pip install --no-cache-dir requests kafka-python
COPY . /app

ENV PYTHONUNBUFFERED=1

CMD ["python", "producer.py"]