FROM python:3.10-slim

WORKDIR /app

# Copier seulement le fichier requirements pour utiliser le cache efficacement
COPY requirements.txt /app/requirements.txt

# Installer toutes les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le code de l’application
COPY . /app

EXPOSE 8501

CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]
